### ISSUE TITLE
localstack helm version showing 0.1.0

### ISSUE THREAD

**Issue by gabor-boros** [everpeace/helm-charts#8]
Hello,

The [Chart](https://github.com/everpeace/helm-charts/blob/master/localstack/Chart.yaml#L4) of localstack show version `0.3.` while the version found by `helm search` shows `0.1.0`.

Output:
```
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
everpeace/localstack	0.1.0        	           	A Helm chart for localstack
```

**Comment by gabor-boros** [comment]
Ping @everpeace

**Comment by everpeace** [comment]
I'm closing this in favor of #7
